### ISSUE TITLE
generator from cargo

### ISSUE THREAD

**Issue by SolatK** [NebulaSS13/Nebula#2501] opened 2022-06-07 21:55 UTC
#### Description of issue
If you buy TEG from cargo it wont work until you call Initialize()

#### Difference between expected and actual behavior
It should work without calling procs manualy

#### Steps to reproduce
1) Buy TEG and 2 circulator from cargo
2) replace reactor generator with new
3) it didnt make power

#### Specific information for locating

/decl/hierarchy/supply_pack/engineering/teg
/decl/hierarchy/supply_pack/engineering/circulator

I think problem is that init calls inside the cargo crate. Manually spawned generator works fine.

#### Length of time in which bug has been known to occur

from bay

#### Client version, Server revision & Game ID

Server Revision: 2a1f9898f9d0dc8636d4d8e8ff2c6a2906323305 - dev - 2022-06-06

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment] 2022-06-07 21:58
Did you try wrenching it after it's in position and set up?

EDIT: or even clicking it? Apparently pulling up the UI should try reconnecting it too.

**Comment by SolatK** [comment] 2022-06-07 23:31
> Did you try wrenching it after it's in position and set up?
> 
> EDIT: or even clicking it? Apparently pulling up the UI should try reconnecting it too.

Yes, i tried everything except reassembling. And for some reason you cant dismantle teg after manual init call

**Comment by MistakeNot4892** [comment] 2024-05-12 14:14
Cannot reproduce this locally on current staging, closing for now.

**Closed as completed by MistakeNot4892** 2024-05-12 14:14 UTC
Labels: bug
