### ISSUE TITLE
Spider Nurse broken???

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#238] opened 2020-03-31 06:29 UTC
#### Description of issue
Dear People Resources,

Today I got bitten by a spider nurse.  All subsequent scans of my person indicated that I should definitely have had a foreign body to remove from my chest.  However, when it came time to remove the foreign bodies, there was nothing there to remove.  A much, much deeper inspection [view vars] of my person revealed that I had [null] implants in me.  Hesitant as I am to assist spiders, as a doctor, I must express concern at their predicament and inability to adequately reproduce.  A xenobiologist's investigation might come in handy for understanding this as well - perhaps we can find new, better ways to fight these creatures with the information gleaned from one sterile spider nurse?

#### Difference between expected and actual behavior
I expected to die at the horrid hatching of these monstrosities.  I'm pleased to report I'm not only alive and well, but alive and well enough to be bothering you!  

#### Steps to reproduce
I recommend using a monkey as your guinea pig.  To recommend anything more sapient would be the height of unethical medical practice.  

Allow the monkey to become riddled with a non-lethal number of spider bites.  Separate monkey and the one who impregnated them with spider eggs, and perform a surgery [or a view variable] to examine the resulting eggs.  We simply must know more!

#### Specific information for locating

Nurse spider fang wombs?  I'm no xenobiologist.  None of this makes sense to me, but it's horrifying all the same.

#### Length of time in which bug has been known to occur

Today is the first time I've encountered this issue.  Today's date is 3/31/2020.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e81a0d8af562878154e6d5b52ce23c64479d15c0 - dev - 2020-03-30
Game ID: b6q-dy1n
Current map: Tradeship Ivenmoth

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

-Surgical Assistant Dessi

**Comment by MistakeNot4892** [comment] 2020-03-31 06:32
https://cdn.discordapp.com/attachments/663522358362898442/694394419641843752/unknown.png

**Comment by babydoll** [comment] 2020-04-27 19:24
Couldn't reproduce this 

![](https://i.imgur.com/sTAAJcB.png)

**Comment by MistakeNot4892** [comment] 2020-07-17 16:05
Haven't seen this since, closing for the time being.

**Closed as completed by MistakeNot4892** 2020-07-17 16:05 UTC
Labels: could not reproduce
