### ISSUE TITLE
neo-avian clothes don't show

### ISSUE THREAD

**Issue by Greenjoe12345** [NebulaSS13/Nebula#4446] opened 2024-09-10 17:35 UTC
#### Description of issue
Clothing doesn't seem to show on neo-avians for some reason, suit items do show, however.
The items also are invisible in the clothing slots in the inventory.

#### Difference between expected and actual behavior
They should have visible clothes.

#### Steps to reproduce
Wear clothes as a birb.

#### Length of time in which bug has been known to occur
Since the first polaris neb test I believe.

#### Client version, Server revision & Game ID
Multiple

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2024-09-17 11:57
Cannot reproduce this on current dev:
![birdclothes](https://github.com/user-attachments/assets/1a7ec6a1-b60e-4e90-9cc3-a8ee49ff4146)

**Comment by MistakeNot4892** [comment] 2024-09-20 13:44
Closing as cannot repro, feel free to reopen with repro info.

**Closed as completed by MistakeNot4892** 2024-09-20 13:44 UTC
Labels: could not reproduce
