### ISSUE TITLE
Blobs spread ludicrously fast.

### ISSUE THREAD

**Issue by chaoko99** [NebulaSS13/Nebula#2118] opened 2021-09-26 02:21 UTC
#### Description of issue
When spawning, blobs will spread and heal at untenable speeds.

#### Difference between expected and actual behavior
Was expecting it to conceivably be combat-able. 

#### Steps to reproduce
Spawn blob or have it randomspawn
Be immediately completely overwhelmed.

#### Specific information for locating

Blob core

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cec-dL43
Current map: ISEO Endeavour

This was done downstream but I don't believe this is a downstream issue.
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2021-09-27 01:25
`ISEO Endeavour` This isn't a Neb map, have you reproduced the bug on Neb main?

**Comment by chaoko99** [comment] 2021-09-27 02:17
https://streamable.com/k7rilv here is an example of it happening on example

**Comment by MistakeNot4892** [comment] 2022-06-12 07:41
Noting after discussion with Noelle that this appears to be due to us fixing the delays in blob processing on SSobj and that previously blobs were slowing down object processing for the entire subsystem.

**Comment by chaoko99** [comment] 2022-06-12 19:28
lmao my favorite kind of timing issue, fair enough. It may be wise to add
some delays there—It's been some time since I played, but they could
consume the entire ship in like ~5 minutes.

**Comment by MistakeNot4892** [comment] 2022-08-05 12:20
Marking this as closed for now as the blob subsystem can be slowed down further if needed.

**Closed as completed by MistakeNot4892** 2022-08-05 12:20 UTC
Labels: bug, refactor artifact
