### ISSUE TITLE
MMI and Zat_Zhing (Scav Specific) Show Evidence Of Change_Species Method Failing

### ISSUE THREAD

**Issue by EvilDrCoconut** [NebulaSS13/Nebula#4376] opened 2024-08-18 20:41 UTC
#### Description of issue
When a player has their body changed, their brain spirit (or mind or whatever) is ejected from the body, despite that the body is fully fine. It requires an admin to take the person's ghost and put it back into the body. Looking into the code of zat_zhing, where the change_appearance method is called, following that stack it looks possible that the error may be handle_pre_spawn from species.dm as it only returns (don't know if it did anything before). 

#### Difference between expected and actual behavior
Expected: when brain gets dumped into a MMI or someone gets "zat_zinged" (change_species) that they will have species changed or be put into MMI.

Actual: removes the persons ghost and considers them dead unless an admin puts them back into the body. In the case of MMI, treats it like body has been destroyed (might need to check more on this, I wrote the zat_zhing code and tested it recently and noticed the issued. Others claim to have similar issue with MMI)

#### Steps to reproduce
Put someone's brain into an mmi (uncertain if this will trigger correctly)
Use a zat_zhing stone on a non-yinglet (Scav-Station specific; know this will trigger response)

#### Specific information for locating

No message, just ejects ghost

#### Length of time in which bug has been known to occur

Uncertain, only knew about it recently in testing the zat_zhing stone. So within last 2 weeks.

#### Client version, Server revision & Game ID

Runtime Version
514.1589
Compiler Version
514.1589
Revision
04e095cc8da9a9fa124d63a9a3488b22b876df90

#### Issue bingo

- [ x] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2024-08-19 04:59
I think this is specifically due to the brain being removed or deleted.

**Comment by MistakeNot4892** [comment] 2024-08-19 05:50
Species issue fixed in #4377.
Cannot reproduce MMI issues on current Neb stable, will need more information about the specific issue being encountered.

**Comment by sirleatherflute** [comment] 2024-08-20 07:32
Oh, I actually had something like that trying to "reanimate" fbp user.
I detached their MMI cause body needed to have everything replaced, and when I plugged it back in, the player was ghosted, but could re-enter, to a "dead" body, at which point I could reconnect their battery and "restart" them.

Also might be entirely different issue, it's been noticed lately, that monkeys go "SSD" after you make them sleep on the surgery table. Their brain is alive, but they remain unconscious.

**Comment by EvilDrCoconut** [comment] 2024-08-23 17:12
apologies, busy week with work and personal training. But yes, this is an issue where the brain is 100% functional, but the ghost is ejected from the body. Let me create a quick video to attach using Scav Station's "zat zhing". As for the MMI, that was reported by others in medical, I was attaching it as it was reported by people who were inserted into it as the same exact issue, ghost being ejected from body. I do not use the mmi enough to know how to verify it.

**Comment by EvilDrCoconut** [comment] 2024-08-23 18:11
i seem to be running into an interesting issue. This only procs on organics. While trying to get a quick video under 10mb's, i had randomly spawned as a non-organic who successfully proc'ed the change_species call

https://github.com/user-attachments/assets/87365565-37e9-4014-a7a6-c453e00158c9

**Comment by EvilDrCoconut** [comment] 2024-08-23 18:12
As an organic though:

https://github.com/user-attachments/assets/5f341ac8-eaaa-41a6-9625-06820c7a3eb0

**Comment by EvilDrCoconut** [comment] 2024-08-23 18:16
The organic's body is updating correctly for parts, and brain is correcting itself for max_health while damage remains at 0. So the brain has nothing happening to it. It seems the ghost is just removed. But for non organics, this is not an issue.

**Comment by MistakeNot4892** [comment] 2024-08-24 00:19
Can you post revision info please?

**Comment by EvilDrCoconut** [comment] 2024-08-27 14:48
sure, thanks for your patience as I go about my daily life

Client Version: 515
Server Revision: 9316a64663c1bcd4348c0bb565f71ad5dbaada06 - Dev-SAR - 2024-08-18

**Comment by MistakeNot4892** [comment] 2024-08-28 01:41
Your branch is way out of date, if you could try to reproduce after pulling in the latest scav main branch that'd be valuable.

**Comment by MistakeNot4892** [comment] 2024-09-20 13:45
Closing as cannot repro, feel free to reopen with repro info if the issue persists after updating to current stable.

**Closed as completed by MistakeNot4892** 2024-09-20 13:45 UTC
Labels: could not reproduce
