### ISSUE TITLE
Airlock don't scan for ID cards in PDA

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1895] opened 2021-07-14 12:54 UTC
#### Description of issue

Title.

#### Difference between expected and actual behavior

Should check for access in id card if it in PDA.

#### Length of time in which bug has been known to occur

Reported today.

#### Client version, Server revision & Game ID

https://github.com/infinitystation/Nebula/commit/79fa623f247071753b5759dcf116078908873126

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by VNLoverMay** [comment] 2021-07-14 15:52
It probably does, but just for clarification, can you check if the PDA you're having issues with has a proper RFID card broadcaster installed? They need that to broadcast access to airlocks and such.

**Comment by MistakeNot4892** [comment] 2021-07-14 22:15
Duplicate of #1610 which couldn't be reproduced. Check if your PDA was on.

**Comment by MistakeNot4892** [comment] 2021-07-20 13:39
Feel free to reopen this if you can reproduce the issue and confirm the PDA is on.

**Closed as completed by MistakeNot4892** 2021-07-20 13:39 UTC
Labels: duplicate
