### ISSUE TITLE
Dead spiders cannot be pulled via grab-move.

### ISSUE THREAD

**Issue by chaoko99** [NebulaSS13/Nebula#2119] opened 2021-09-26 02:58 UTC
#### Description of issue
Spiders can't be pulled once grabbed. The grab will immediately release.

#### Difference between expected and actual behavior
Grab spider and pull it around.
instead, the grab releases.

#### Steps to reproduce
Grab spider, move.

#### Specific information for locating

spider

#### Length of time in which bug has been known to occur

Likely since grabs were refactored to replace pulling.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: ced-anl8
Current map: ISEO Endeavour

Downstream but not something we changed.
#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds -- Have not had a second round with spiders.
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2021-09-28 01:53
Can't reproduce on stable. Spiders resist grabs, are you sure it wasn't that?

**Comment by chaoko99** [comment] 2021-09-28 01:55
I missed an important detail, they resist grabs even when DEAD. sometimes you can pull them one tile. Pushing them by pull/clicking works.

**Comment by chaoko99** [comment] 2021-09-28 01:55
The release happens on movement.

**Comment by MistakeNot4892** [comment] 2021-09-28 01:57
Can repro the grab breaking when they're dead, can't repro them resisting when dead.

**Comment by MistakeNot4892** [comment] 2022-05-14 12:56
Fixed on staging.

**Closed as completed by MistakeNot4892** 2022-05-14 12:56 UTC
Labels: bug, stable
