### ISSUE TITLE
disposals ejection chute glitch

### ISSUE THREAD

**Issue by ZirconiumWit** [NebulaSS13/Nebula#148] opened 2020-03-15 07:18 UTC
#### Description of issue
disposals ejection chute works when a mob enters it or if an item is thrown in, but objects entering the disposals ejection chute by way of conveyor belt simply sit on the tile the chute is on without going in.  

#### Difference between expected and actual behavior
Until recently, conveyor belts could work properly with disposals ejection chute.  

#### Steps to reproduce
use conveyor belt to push trash into the disposals chute

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e81a0d8af562878154e6d5b52ce23c64479d15c0 - brickwork - 2020-03-15
Game ID: b6b-bfGF
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by afterthought2** [comment] 2020-03-19 08:13
Can't reproduce. Are you sure the direction the chute was facing was correct? If so, can you link a mapped, nonworking setup?

**Comment by ZirconiumWit** [comment] 2020-03-24 02:30
chute is the one on the scavstation downstream.  posted here because it worked before a machine update.

Below image verifies direction is west.

![image](https://user-images.githubusercontent.com/59771903/77381952-175b7300-6d4d-11ea-94f2-afcf4aaa6e2f.png)

turning on conveyor belt simply places garbage atop the disposals chute.

![image](https://user-images.githubusercontent.com/59771903/77382100-6f927500-6d4d-11ea-901a-baf71f9670cd.png)

but throwing an object into the chute causes it to eject out into space as it ought to.

![image](https://user-images.githubusercontent.com/59771903/77382144-8fc23400-6d4d-11ea-9f10-66266b966732.png)

**Comment by afterthought2** [comment] 2020-04-04 23:53
This is caused by 
```

/atom/movable/CanPass(atom/movable/mover, turf/target, height=1.5, air_group = 0)
	. = ..() || (mover && !mover.density)
```
`..()` is false here. If you move something to the disposals outlet, it will bump it if this returns false, i.e. if the mover is not dense, it will not bump it.

Obviously this can be fixed by overriding on disposals, but seems like this is a pretty general change of behavior, so pinging @MistakeNot4892 for suggestions (his change).

**Comment by MistakeNot4892** [comment] 2020-12-08 14:27
Seems to be fixed on dev, everything went in via conveyor, throw and active movement.

**Closed as completed by MistakeNot4892** 2020-12-08 14:27 UTC
Labels: question
