### ISSUE TITLE
Animals don't move sometimes

### ISSUE THREAD

**Issue by quardbreak** [NebulaSS13/Nebula#1585] opened 2021-04-29 12:48 UTC
#### Description of issue

After spawning, Ian and mouses can don't move or just start staying on place.

#### Difference between expected and actual behavior

Animals should be able regularly move if their AI allow that.

#### Steps to reproduce

1. Spawn Ian
2. See it doesn't move in some rounds.

#### Specific information for locating

Unsure, but might AI's controller.

#### Length of time in which bug has been known to occur

Maybe since AI datumize.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2021-06-30 06:48
I've seen this occasionally as well but as yet have no idea how to reproduce it.

**Comment by MistakeNot4892** [comment] 2022-11-01 04:36
This may be due to non-living mobs not counting as observers, and simplemobs not processing Life() when unobserved.

**Comment by MistakeNot4892** [comment] 2022-11-16 03:24
Closing this unless it can be reproduced by a living mob observing them.

**Closed as completed by MistakeNot4892** 2022-11-16 03:24 UTC
Labels: bug
