### ISSUE TITLE
Hair Remover Not Working

### ISSUE THREAD

**Issue by Aleuph** [NebulaSS13/Nebula#4472] opened 2024-09-17 23:53 UTC
#### Description of issue

Hair remover appears to not be working on any target. Sprayed or injected, reproduced by Sharah and myself over the course of two rounds.

#### Difference between expected and actual behavior

Funny chem should make silly ratbird look like a mole rat and not do... Well, nothing at all.

#### Steps to reproduce

Make funny chem. Inject target. Watch nothing occur

#### Specific information for locating

Hair Remover chemical

#### Length of time in which bug has been known to occur

Noticed this literally earlier today. Round ended and I mentioned it needed further testing, Sharah obliged and can confirm there is no reaction upon subject experimentation.

#### Client version, Server revision & Game ID

Game ID: cvK-dCsJ
Server Rev: 3c8781c7a1ad61e0d87bdb09c03f87d00a270f98
Client Ver: 514.1589

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2024-09-17 23:53
It's a contact reagent not an injectable.

**Comment by Aleuph** [comment] 2024-09-17 23:54
Sprayed it too

**Comment by Aleuph** [comment] 2024-09-17 23:54
To be certain as I was not

**Comment by Aleuph** [comment] 2024-09-17 23:55
> It's a contact reagent not an injectable.
I'll figure out how to use github eventually

**Comment by MistakeNot4892** [comment] 2024-09-18 02:21
Cannot reproduce on stable, spraying a Taj with hair remover removed fur and hair.

**Comment by MistakeNot4892** [comment] 2024-09-20 13:40
Closing as cannot repro, feel free to reopen with specific info for repro.

**Closed as completed by MistakeNot4892** 2024-09-20 13:40 UTC
Labels: could not reproduce
