### ISSUE TITLE
Radial menu issues

### ISSUE THREAD

**Issue by OlyMoley7** [NebulaSS13/Nebula#4362] opened 2024-08-16 02:58 UTC
#### Description of issue
Radial menus don't work as intended, random choice instead of the option picked or nothing at all

#### Difference between expected and actual behavior
Click on toggle safety, does nothing
Click on suture artery, has a 1 in (however many options there are in the menu) chance of doing what was issued, will either sew the wound back together, suture an artery or link tendons

#### Steps to reproduce
Open a radial menu and interact with it.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2024-08-16 03:05
Regarding the surgery issue, do you have surgery skills selected?
Toggling safety worked fine on Neb dev a few hours ago when I did the fix for unloading.

**Comment by MistakeNot4892** [comment] 2024-08-16 10:45
Seems like I clobbered gun changes after testing, #4367 fixes the alt interaction.
Surgery stuff seems to be skill related, cannot reproduce your issue except with untrained Anatomy or Medicine, which is an intentional consequence of a skill failure.

**Comment by OlyMoley7** [comment] 2024-08-17 08:35
> Regarding the surgery issue, do you have surgery skills selected? Toggling safety worked fine on Neb dev a few hours ago when I did the fix for unloading.

This was seen with a character with trained anatomy and medical

**Comment by MistakeNot4892** [comment] 2024-08-19 05:29
Cannot reproduce this on Neb dev. Will need some more specific reproduction steps if they come up.

**Comment by MistakeNot4892** [comment] 2024-09-17 12:26
I think this may have been due to the UX issues with labels that are fixed on current dev. Going to call this closed for now, feel free to reopen with specific reproduction steps if it persists.

**Closed as completed by MistakeNot4892** 2024-09-17 12:26 UTC
Labels: could not reproduce
