### ISSUE TITLE
Removed floor tile = removed decal

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [NebulaSS13/Nebula#4181] opened 2024-07-09 14:39 UTC
#### Description of issue

When I use a crowbar to peel off the tile on which the decal was applied, and then put this tile back in place, the decal on the tile disappears.

#### Difference between expected and actual behavior

Decal should stay. Like on OnyxBay or Polaris

#### Steps to reproduce

1. Have a nice tile with decal on it
2. Use a crowbar on it
3. Get a tile item
4. Place a tile back
5. See - no decal because it's gone

#### Specific information for locating

-

#### Length of time in which bug has been known to occur

Any time

#### Client version, Server revision & Game ID

Last one or any one

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2024-07-09 16:49
This is an intentional change, voted for on the Discord.
![Screenshot_20240710-024641_Discord](https://github.com/NebulaSS13/Nebula/assets/2468979/4dae323a-2845-4fb3-97e1-6453ea13fb65)

**Comment by ArmolitskiyCarpoeb** [comment] 2024-07-09 16:53
> This is an intentional change, voted for on the Discord. 

Both variants are bad why not to make it save decal? So you have a tile item (stack) with decal on it and you can place it back or even in another place. It is how it works on OnyxBay and it's just better than removing decals when you remove a floor tile

**Comment by MistakeNot4892** [comment] 2024-07-09 17:10
Saving decals on the tile has its own issues:
- how do you tell what decals are saved on a tile?
- how do you handle merging or splitting tile stacks with decals?
- can you remove decals without putting the tile down as a floor?

If someone wanted to open a PR implementing what you're after I would be happy to review it, but the current arrangement is intentional, not a bug/issue.

**Comment by ArmolitskiyCarpoeb** [comment] 2024-07-09 17:22
> Saving decals on the tile has its own issues:
> 
> * how do you tell what decals are saved on a tile?
> * how do you handle merging or splitting tile stacks with decals?
> * can you remove decals without putting the tile down as a floor?
> 
> If someone wanted to open a PR implementing what you're after I would be happy to review it, but the current arrangement is intentional, not a bug/issue.

1. No, you can't. Not a big problem, just put it down on the plating
2. No merging then or merging with the same tile+decal only
3. By using acids or some chemical? I don't know and it's not very necessary imo
Can't even remember how other codebases answered those questions

**Comment by MistakeNot4892** [comment] 2024-07-11 10:55
Per Discord, this appears to have been implemented on the poster's fork, so closing as not an issue for Neb.

**Closed as completed by MistakeNot4892** 2024-07-11 10:55 UTC
